/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author Chriss
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        dpnInicio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuRegistrar = new javax.swing.JMenu();
        mItemTrabajador = new javax.swing.JMenuItem();
        mItemEmpresa = new javax.swing.JMenuItem();
        mItemProveedor = new javax.swing.JMenuItem();
        menuListado = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hostal Doña Clarita");

        dpnInicio.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout dpnInicioLayout = new javax.swing.GroupLayout(dpnInicio);
        dpnInicio.setLayout(dpnInicioLayout);
        dpnInicioLayout.setHorizontalGroup(
            dpnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        dpnInicioLayout.setVerticalGroup(
            dpnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jMenu1.setText("Usuarios");

        menuRegistrar.setText("Registrar");

        mItemTrabajador.setText("Trabajador");
        mItemTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemTrabajadorActionPerformed(evt);
            }
        });
        menuRegistrar.add(mItemTrabajador);

        mItemEmpresa.setText("Empresa");
        mItemEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemEmpresaActionPerformed(evt);
            }
        });
        menuRegistrar.add(mItemEmpresa);

        mItemProveedor.setText("Proveedor");
        mItemProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemProveedorActionPerformed(evt);
            }
        });
        menuRegistrar.add(mItemProveedor);

        jMenu1.add(menuRegistrar);

        menuListado.setText("Listado");
        menuListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListadoActionPerformed(evt);
            }
        });
        jMenu1.add(menuListado);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnInicio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpnInicio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    registrarEmpresa _empresa = new registrarEmpresa();
    private void mItemEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemEmpresaActionPerformed
        if (!_empresa.isShowing()){
            dpnInicio.add(_empresa);
            _empresa.show();
        }
    }//GEN-LAST:event_mItemEmpresaActionPerformed

    registrarEmpleados _empleados = new registrarEmpleados();
    private void mItemTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemTrabajadorActionPerformed
        if (!_empleados.isShowing()){
            dpnInicio.add(_empleados);
            _empleados.show();
        }
    }//GEN-LAST:event_mItemTrabajadorActionPerformed

    listadoUsuarios _usuarios = new listadoUsuarios();
    private void menuListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListadoActionPerformed

        if (!_usuarios.isShowing()){
            dpnInicio.add(_usuarios);
            _usuarios.show();
        }
    }//GEN-LAST:event_menuListadoActionPerformed

    registrarProveedor _proveedor = new registrarProveedor();
    private void mItemProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemProveedorActionPerformed
        if (!_proveedor.isShowing()){
            dpnInicio.add(_proveedor);
            _proveedor.show();
        }
    }//GEN-LAST:event_mItemProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnInicio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mItemEmpresa;
    private javax.swing.JMenuItem mItemProveedor;
    private javax.swing.JMenuItem mItemTrabajador;
    private javax.swing.JMenuItem menuListado;
    private javax.swing.JMenu menuRegistrar;
    // End of variables declaration//GEN-END:variables
}
