/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.main;
import com.google.gson.Gson;
import java.text.DateFormat;
import org.json.JSONObject;
/**
 *
 * @author Chris
 */
public class recepcionProductos extends javax.swing.JInternalFrame {
    main _main = new main();
    Object[] productosData;
    Object[] tipoProductosData;
    Object[] familiaData;
    Gson gson = new Gson();
    /**
     * Creates new form recepcionProductos
     */
    public recepcionProductos() {
        initComponents();
        llenarCombo();
    }

    private void llenarCombo(){
        String productos = _main.listaProductos();
        productosData = gson.fromJson(productos, Object[].class);
        
        for (int i = 0; i < productosData.length; i++){
            String producto = gson.toJson(productosData[i]);
            JSONObject jsonObject = new JSONObject(producto);
            comboProducto.addItem(jsonObject.get("NOMBRE").toString());
        }
        
        String tipoProductos = _main.listaTipoProductos();
        tipoProductosData = gson.fromJson(tipoProductos, Object[].class);
        
        for (int i = 0; i < tipoProductosData.length; i++){
            String tipoProducto = gson.toJson(tipoProductosData[i]);
            JSONObject jsonObject = new JSONObject(tipoProducto);
            comboTipoProducto.addItem(jsonObject.get("NOMBRE").toString());
        }
        
        String familias = _main.listaFamilias();
        familiaData = gson.fromJson(familias, Object[].class);
        
        for (int i = 0; i < familiaData.length; i++){
            String familia = gson.toJson(familiaData[i]);
            JSONObject jsonObject = new JSONObject(familia);
            comboFamiliaProducto.addItem(jsonObject.get("NOMBRE").toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboProducto = new javax.swing.JComboBox();
        comboTipoProducto = new javax.swing.JComboBox();
        txtPrecio = new javax.swing.JTextField();
        comboFamiliaProducto = new javax.swing.JComboBox();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtStockCritico = new javax.swing.JTextField();
        calFecha = new com.toedter.calendar.JCalendar();
        btnAceptar = new javax.swing.JButton();

        jLabel1.setText("Tipo de Producto");

        jLabel2.setText("Familia de Producto");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Cantidad");

        jLabel6.setText("Fecha de Vencimiento");

        jLabel7.setText("Stock Crítico");

        jLabel8.setText("Precio Unitario");

        jLabel9.setText("Producto");

        jLabel10.setText("Stock");

        comboProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductoActionPerformed(evt);
            }
        });

        txtPrecio.setEditable(false);

        txtDescripcion.setEditable(false);

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        txtStock.setEditable(false);

        txtStockCritico.setEditable(false);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboProducto, 0, 108, Short.MAX_VALUE)
                            .addComponent(txtDescripcion)
                            .addComponent(txtPrecio)
                            .addComponent(comboTipoProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboFamiliaProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(calFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(txtStockCritico, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel10))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(txtStock)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtStockCritico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(calFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboFamiliaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btnAceptar)))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        DateFormat df = DateFormat.getDateInstance();
        String fecha = df.format(calFecha.getDate());
        Object[] familiaSelec = comboFamiliaProducto.getSelectedObjects();
        Object[] productoSelec = comboProducto.getSelectedObjects();
        Object[] tipoSelec = comboTipoProducto.getSelectedObjects();
       int familiaId = 0;
       int productoId = 0;
       int tipoId = 0;
       int precio = 0;
       String descripcion = txtDescripcion.getText();
       int cantidad = Integer.parseInt(txtCantidad.getText());
       int stock = Integer.parseInt(txtCantidad.getText());
       int stockCritico = Integer.parseInt(txtCantidad.getText());
       
        for (int i = 0; i < familiaData.length; i++){
            String familia = gson.toJson(familiaData[i]);
            JSONObject jsonObject = new JSONObject(familia);
            if (familiaSelec[0].toString().equals(jsonObject.get("NOMBRE").toString())){
                familiaId = new Double(jsonObject.get("ID").toString()).intValue();
            }
        }
        
        for (int i = 0; i < productosData.length; i++){
            String producto = gson.toJson(productosData[i]);
            JSONObject jsonObject = new JSONObject(producto);
            System.out.println(jsonObject);
            System.out.println(jsonObject.get("NOMBRE").toString());
            if (productoSelec[0].toString().equals(jsonObject.get("NOMBRE").toString())){
                productoId = new Double(jsonObject.get("ID").toString()).intValue();
                precio = new Double(jsonObject.get("PRECIO").toString()).intValue();
            }
        }
        
         for (int i = 0; i < tipoProductosData.length; i++){
            String tipos = gson.toJson(tipoProductosData[i]);
            JSONObject jsonObject = new JSONObject(tipos);
            if (tipoSelec[0].toString().equals(jsonObject.get("NOMBRE").toString())){
                tipoId = new Double(jsonObject.get("ID").toString()).intValue();
            }
        }
         
         main _main = new main();
         
         //boolean _resp = main.createRecepcionProducto( newCodigo, java.lang.String newNombre, int newPrecio, int newTipoProductoId, int newFamilia, java.lang.String newDescripcion, int newStock, int newStockCritico)
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void comboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductoActionPerformed
        Object[] productoSelec = comboProducto.getSelectedObjects();
        
        for (int i = 0; i < productosData.length; i++){
            String producto = gson.toJson(productosData[i]);
                JSONObject jsonObject = new JSONObject(producto);
                if (productoSelec[0].toString().equals(jsonObject.get("NOMBRE").toString())){
                    txtDescripcion.setText(jsonObject.get("DESCRIPCION").toString());
                    txtPrecio.setText(jsonObject.get("PRECIO").toString());
                    txtStock.setText(jsonObject.get("STOCK").toString());
                    txtStockCritico.setText(jsonObject.get("STOCK_CRITICO").toString());
                }
        }
    }//GEN-LAST:event_comboProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private com.toedter.calendar.JCalendar calFecha;
    private javax.swing.JComboBox comboFamiliaProducto;
    private javax.swing.JComboBox comboProducto;
    private javax.swing.JComboBox comboTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtStockCritico;
    // End of variables declaration//GEN-END:variables
}
