/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.main;
import com.google.gson.Gson;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author Chris
 */
public class registrarPlatos extends javax.swing.JInternalFrame {

    Object[] serviciosData;
    Gson gson = new Gson();
    /**
     * Creates new form registrarPlatos
     */
    public registrarPlatos() {
        initComponents();
        llenarCombo();
    }
    private void llenarCombo(){
        main _main = new main();
        String servicios = _main.listaServicios();
        serviciosData = gson.fromJson(servicios, Object[].class);
        Map<Integer, String> mapa = new HashMap<>();
        for (int i = 0; i < serviciosData.length; i++){
            String servicio = gson.toJson(serviciosData[i]);
            JSONObject jsonObject = new JSONObject(servicio);
            comboServicios.addItem(jsonObject.get("NOMBRE").toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboServicios = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtPlato = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        setResizable(true);
        setTitle("Registrar Platos");

        jLabel1.setText("Tipo de Servicio");

        jLabel2.setText("Nombre Plato");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPlato)
                    .addComponent(comboServicios, 0, 103, Short.MAX_VALUE))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnRegistrar)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombre = txtPlato.getText();
        int tipoServicioId = 0;
        
        Object[] servicioSelec = comboServicios.getSelectedObjects();
        for (int i = 0; i < serviciosData.length; i++){
            String servicio = gson.toJson(serviciosData[i]);
            JSONObject jsonObject = new JSONObject(servicio);
            if (servicioSelec[0].toString().equals(jsonObject.get("NOMBRE").toString())){
                tipoServicioId = new Double(jsonObject.get("ID").toString()).intValue();
            }
        }
        main _main = new main();
        
        boolean _resp = _main.createPlatos(nombre, tipoServicioId);
        if(!_resp){
            JOptionPane.showMessageDialog(rootPane, "Error al Registrar el plato");
            return;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Plato registrado");
            return;
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox comboServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPlato;
    // End of variables declaration//GEN-END:variables
}
